### ISSUE TITLE
Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE

### ISSUE THREAD

**Issue by mdmmdm** [seryal/sywebsocket#1]
Hi
When a client connects to a server on lazarus, in the OnClientConected procedure, I immediately send a message to the client, the client then immediately crashes with an error
WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: net :: ERR_INVALID_HTTP_RESPONSE

But, if I do not immediately send a message when the client connects, but send it by pressing a button, everything is fine

**Comment by seryal** [comment]
O! Thanks. Yes it's bug. I will fix it.

Because OnClientConected event occurs when there is TCP connection and not after a handshake.
And trying to send a message immediately you will get error.

**Comment by seryal** [comment]
I'm in work travel now. I plan to fix this after 03 october.

**Comment by mdmmdm** [comment]
Thanks.
